baseURL = "https://ikhsanalatsary.github.io/myslide"
languageCode = "en-us"
title = "Mastering Javascripit: Jquery"
theme = "docdock"

[params]
editURL = "" # https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)

[outputs]
home = [ "HTML", "RSS", "JSON"]
